"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/admin-session";
import { vehicleInputSchema, type VehicleInput } from "@/lib/admin/vehicle-schema";
import { del } from "@vercel/blob";
import { isVercelBlobUrl } from "@/lib/blob";

type ActionResult = { ok: boolean; message: string; id?: string; fieldErrors?: Record<string, string[]> };
function revalidate(slug: string, oldSlug?: string) { ["/admin", "/admin/vehicles", "/fr", "/ar", "/fr/voitures", "/ar/cars", `/fr/voitures/${slug}`, `/ar/cars/${slug}`, oldSlug && `/fr/voitures/${oldSlug}`, oldSlug && `/ar/cars/${oldSlug}`].filter(Boolean).forEach((path) => revalidatePath(path as string)); }
export async function discardStagedVehicleImage(url: string) { await requireAdmin(); if (!isVercelBlobUrl(url)) return; try { await del(url); } catch { /* A failed cleanup must not affect the unsaved form state. */ } }
async function validate(input: VehicleInput) { const parsed = vehicleInputSchema.safeParse(input); if (!parsed.success) return { error: { ok: false, message: "Veuillez corriger les champs indiqués.", fieldErrors: parsed.error.flatten().fieldErrors } as ActionResult }; const category = await prisma.vehicleCategory.findFirst({ where: { id: parsed.data.categoryId, active: true }, select: { id: true } }); if (!category) return { error: { ok: false, message: "Catégorie invalide." } as ActionResult }; const selectedMain = parsed.data.images.findIndex((image) => image.isMain); return { data: { ...parsed.data, images: parsed.data.images.map((image, index) => ({ ...image, isMain: index === (selectedMain >= 0 ? selectedMain : 0), displayOrder: index })) } }; }
export async function createVehicle(input: VehicleInput): Promise<ActionResult> { await requireAdmin(); const checked = await validate(input); if ("error" in checked && checked.error) return checked.error; const duplicate = await prisma.vehicle.findUnique({ where: { slug: checked.data.slug }, select: { id: true } }); if (duplicate) return { ok: false, message: "Ce slug est déjà utilisé.", fieldErrors: { slug: ["Choisissez un slug unique."] } }; try { const vehicle = await prisma.$transaction((tx) => tx.vehicle.create({ data: { ...checked.data, images: { create: checked.data.images } } })); revalidate(vehicle.slug); return { ok: true, message: "Véhicule ajouté.", id: vehicle.id }; } catch { return { ok: false, message: "Impossible d’enregistrer le véhicule." }; } }
export async function updateVehicle(id: string, input: VehicleInput): Promise<ActionResult> { await requireAdmin(); if (!/^c[a-z0-9]+$/i.test(id)) return { ok: false, message: "Véhicule invalide." }; const checked = await validate(input); if ("error" in checked && checked.error) return checked.error; const existing = await prisma.vehicle.findUnique({ where: { id }, select: { slug: true, images: { select: { url: true } } } }); if (!existing) return { ok: false, message: "Véhicule introuvable." }; const duplicate = await prisma.vehicle.findFirst({ where: { slug: checked.data.slug, NOT: { id } }, select: { id: true } }); if (duplicate) return { ok: false, message: "Ce slug est déjà utilisé.", fieldErrors: { slug: ["Choisissez un slug unique."] } }; try { await prisma.$transaction(async (tx) => { await tx.vehicleImage.deleteMany({ where: { vehicleId: id } }); await tx.vehicle.update({ where: { id }, data: { ...checked.data, images: { create: checked.data.images } } }); }); const retainedUrls = new Set(checked.data.images.map((image) => image.url)); const removedBlobUrls = existing.images.map((image) => image.url).filter((url) => !retainedUrls.has(url) && isVercelBlobUrl(url)); await Promise.allSettled(removedBlobUrls.map((url) => del(url))); revalidate(checked.data.slug, existing.slug); return { ok: true, message: "Modifications enregistrées.", id }; } catch { return { ok: false, message: "Impossible d’enregistrer les modifications." }; } }
