"use client";

import { useState, useTransition } from "react";
import { Star, ToggleLeft, Eye } from "lucide-react";
import { updateVehicleAvailability, toggleVehicleActive, toggleVehicleFeatured } from "@/app/admin/(protected)/actions";

export function VehicleActions({ id, slug, active, featured, availability }: { id: string; slug: string; active: boolean; featured: boolean; availability: "AVAILABLE" | "UNAVAILABLE" | "MAINTENANCE" | "RESERVED" }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); const run = (task: () => Promise<{ ok: boolean; message: string }>) => startTransition(async () => { const result = await task(); setMessage(result.message); });
  return <div className="flex flex-wrap items-center gap-2"><a href={`/fr/voitures/${slug}`} target="_blank" rel="noreferrer" className="grid size-9 place-items-center rounded-lg border border-slate-200 text-[#10233c] hover:bg-slate-50" aria-label="Voir sur le site"><Eye className="size-4" /></a><select aria-label="Modifier la disponibilité" disabled={pending} value={availability} onChange={(event) => run(() => updateVehicleAvailability({ id, availability: event.target.value as "AVAILABLE" | "UNAVAILABLE" | "MAINTENANCE" | "RESERVED" }))} className="h-9 rounded-lg border border-slate-200 bg-white px-2 text-xs font-semibold"><option value="AVAILABLE">Disponible</option><option value="UNAVAILABLE">Indisponible</option><option value="MAINTENANCE">En entretien</option><option value="RESERVED">Réservée</option></select><button disabled={pending} onClick={() => { if (active && !confirm("Cette voiture ne sera plus visible sur le site public.")) return; run(() => toggleVehicleActive({ id })); }} className="grid size-9 place-items-center rounded-lg border border-slate-200 text-[#10233c] hover:bg-slate-50 disabled:opacity-50" aria-label={active ? "Masquer le véhicule" : "Activer le véhicule"}><ToggleLeft className="size-4" /></button><button disabled={pending} onClick={() => run(() => toggleVehicleFeatured({ id }))} className={`grid size-9 place-items-center rounded-lg border disabled:opacity-50 ${featured ? "border-amber-300 bg-amber-50 text-amber-700" : "border-slate-200 text-[#10233c] hover:bg-slate-50"}`} aria-label={featured ? "Retirer de la sélection" : "Mettre en avant"}><Star className="size-4" /></button>{message && <span role="status" className="basis-full text-xs font-medium text-slate-600">{message}</span>}</div>;
}
