"use client";

import { motion, useReducedMotion } from "framer-motion";
import { MapPin, MessageCircle, Phone } from "lucide-react";
import { FormEvent, useState } from "react";
import { getWhatsAppUrl, generalWhatsAppMessage } from "@/lib/whatsapp";
import type { PublicPickupLocation, PublicSiteSettings } from "@/lib/data/vehicle-mapper";

type Field = "name" | "phone" | "vehicle" | "departure" | "returnLocation" | "startDate" | "endDate";
const fieldClass = "mt-1.5 h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-[#0b5aa7] focus:ring-2 focus:ring-blue-100";

export function ContactSection({ rtl = false, locations = [], settings }: { rtl?: boolean; locations?: PublicPickupLocation[]; settings?: PublicSiteSettings }) {
  const reduceMotion = useReducedMotion(); const [errors, setErrors] = useState<Partial<Record<Field, string>>>({});
  const copy = rtl ? { label: "تواصل", title: "أخبرنا بما تحتاجه", description: "أرسل تواريخك ونوع السيارة التي تبحث عنها. سيجيبك فريقنا مباشرة بالتوفر والثمن المناسب.", reassurance: "طلبك يُرسل مباشرة إلى واتساب، دون دفع أو التزام عبر الموقع.", call: "اتصل بالوكالة", write: "اكتب لنا على واتساب", location: "سيدي قاسم، المغرب", form: "أرسل طلبك", optional: "اختياري", submit: "أرسل طلبي عبر واتساب", required: "هذا الحقل مطلوب.", invalidPhone: "أدخل رقم هاتف صالحاً.", labels: ["الاسم الكامل", "رقم الهاتف", "السيارة المطلوبة", "مكان الانطلاق", "مكان العودة", "تاريخ الانطلاق", "تاريخ العودة", "رسالة"] } : { label: "CONTACT", title: "Parlez-nous de votre besoin", description: "Indiquez vos dates et le type de voiture recherché. Notre équipe vous répondra directement avec les disponibilités et le tarif adapté.", reassurance: "Votre demande est envoyée directement sur WhatsApp, sans paiement ni engagement en ligne.", call: "Appeler l’agence", write: "Écrire sur WhatsApp", location: "Sidi Kacem, Maroc", form: "Envoyer une demande", optional: "optionnel", submit: "Envoyer ma demande sur WhatsApp", required: "Ce champ est obligatoire.", invalidPhone: "Indiquez un numéro de téléphone valide.", labels: ["Nom complet", "Numéro de téléphone", "Voiture souhaitée", "Lieu de départ", "Lieu de retour", "Date de départ", "Date de retour", "Message"] };
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()) as Record<Field | "message", string>; const next: Partial<Record<Field, string>> = {}; (Object.keys({ name: 1, phone: 1, vehicle: 1, departure: 1, returnLocation: 1, startDate: 1, endDate: 1 }) as Field[]).forEach((key) => { if (!values[key]?.trim()) next[key] = copy.required; }); if (values.phone && !/[0-9]{8,}/.test(values.phone.replace(/\D/g, ""))) next.phone = copy.invalidPhone; setErrors(next); if (Object.keys(next).length) return; const message = `Bonjour Vay Cars Location, je souhaite faire une demande de location.\n\nNom : ${values.name}\nTéléphone : ${values.phone}\nVoiture souhaitée : ${values.vehicle}\nLieu de départ : ${values.departure}\nLieu de retour : ${values.returnLocation}\nDate de départ : ${values.startDate}\nDate de retour : ${values.endDate}\nMessage : ${values.message || ""}`; window.open(getWhatsAppUrl(message), "_blank", "noopener,noreferrer"); }
  const names: Field[] = ["name", "phone", "vehicle", "departure", "returnLocation", "startDate", "endDate"];
  const types: Record<Field, string> = { name: "text", phone: "tel", vehicle: "text", departure: "text", returnLocation: "text", startDate: "date", endDate: "date" };
  const location = locations[0]?.name ?? copy.location; const locationListId = rtl ? "contact-pickup-locations-ar" : "contact-pickup-locations-fr"; const phone = settings?.phone ?? "06 84 04 01 55"; const whatsappNumber = settings?.whatsappNumber;
  return <section id="contact" className="bg-white py-20 sm:py-24" dir={rtl ? "rtl" : "ltr"}><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:items-start lg:gap-16 lg:px-8">
    <motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.48 }}><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">{copy.label}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-[#10233c] sm:text-4xl">{copy.title}</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">{copy.description}</p><p className="mt-5 text-sm leading-6 text-slate-500">{copy.reassurance}</p><div className="mt-8 grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.35 }} className="relative flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold text-[#10233c]"><Phone className="size-5 shrink-0 text-[#0b5aa7]" />{copy.call}<a href={`tel:+212${phone.replace(/\D/g, "").replace(/^0/, "")}`} className="absolute inset-0" aria-label={copy.call} /></motion.div><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.35, delay: reduceMotion ? 0 : 0.08 }} className="relative flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold text-[#10233c]"><MessageCircle className="size-5 shrink-0 text-[#0b5aa7]" />{copy.write}<a href={getWhatsAppUrl(generalWhatsAppMessage, whatsappNumber)} target="_blank" rel="noreferrer" className="absolute inset-0" aria-label={copy.write} /></motion.div><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.35, delay: reduceMotion ? 0 : 0.16 }} className="flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold text-[#10233c]"><MapPin className="size-5 shrink-0 text-[#0b5aa7]" />{location}</motion.div></div></motion.div>
    <motion.div initial={{ opacity: 0, x: reduceMotion ? 0 : rtl ? -20 : 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.15 }} transition={{ duration: 0.5 }} className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-5 shadow-[0_14px_35px_rgba(15,35,60,.08)] sm:p-7"><h3 className="text-xl font-bold text-[#10233c]">{copy.form}</h3><form noValidate onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2">{names.map((name, index) => <label key={name} className={name === "vehicle" ? "sm:col-span-2" : ""}><span className="text-sm font-semibold text-[#10233c]">{copy.labels[index]} <span className="text-[#0b5aa7]" aria-hidden="true">*</span></span><input name={name} type={types[name]} list={name === "departure" || name === "returnLocation" ? locationListId : undefined} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `${name}-error` : undefined} onChange={() => errors[name] && setErrors((current) => ({ ...current, [name]: undefined }))} className={fieldClass} />{errors[name] && <span id={`${name}-error`} className="mt-1 block text-xs font-medium text-red-600">{errors[name]}</span>}</label>)}<datalist id={locationListId}>{locations.map((pickup) => <option key={pickup.id} value={pickup.name} />)}</datalist><label className="sm:col-span-2"><span className="text-sm font-semibold text-[#10233c]">{copy.labels[7]} <span className="font-normal text-slate-500">({copy.optional})</span></span><textarea name="message" rows={4} className={`${fieldClass} h-auto py-3`} /></label><button className="sm:col-span-2 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#16a34a] px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-[#15803d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0b5aa7] focus-visible:ring-offset-2" type="submit"><MessageCircle className="size-4" />{copy.submit}</button></form></motion.div>
  </div></section>;
}
