"use client";

import Link from "next/link";
import { motion, useMotionValueEvent, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowLeft, ArrowRight, CalendarDays, CarFront, CheckCircle2, ClipboardCheck, MessageCircle, ShieldCheck, Sparkles, UserRoundCheck } from "lucide-react";
import { useRef, useState } from "react";
import { generalWhatsAppMessage } from "@/lib/whatsapp";
import { WhatsAppLink } from "./whatsapp-link";

const frenchSteps = [[CarFront, "Choisissez votre véhicule", "Consultez notre sélection et choisissez la voiture adaptée à votre trajet."], [CalendarDays, "Indiquez vos dates", "Précisez la date de départ, la date de retour et le lieu souhaité."], [MessageCircle, "Recevez votre tarif", "Notre équipe vérifie la disponibilité et vous communique le tarif selon votre période."], [CheckCircle2, "Confirmez sur WhatsApp", "Finalisez votre réservation directement avec Vay Cars Location."]] as const;
const arabicSteps = [[CarFront, "اختر سيارتك", "اطّلع على مجموعتنا واختر السيارة المناسبة لرحلتك."], [CalendarDays, "حدد تواريخك", "أدخل تاريخ الانطلاق والعودة والمكان الذي تريده."], [MessageCircle, "احصل على عرضك", "يتحقق فريقنا من التوفر ويبلغك بالسعر حسب الفترة."], [CheckCircle2, "أكد عبر واتساب", "أكمل حجزك مباشرة مع Vay Cars Location."]] as const;
const frenchBenefits = [[Sparkles, "Véhicules propres et entretenus", "Chaque voiture est préparée pour offrir une expérience confortable et rassurante."], [MessageCircle, "Réponse rapide sur WhatsApp", "Recevez rapidement les informations sur la disponibilité et le tarif."], [CarFront, "Service local à Sidi Kacem", "Une agence proche de ses clients et disponible pour les accompagner."], [ClipboardCheck, "Conditions claires", "Les informations importantes sont communiquées avant la confirmation."], [ShieldCheck, "Véhicules adaptés à vos besoins", "Des modèles économiques, citadins, berlines et SUV pour différents trajets."], [UserRoundCheck, "Accompagnement personnalisé", "Notre équipe vous guide avant et pendant votre location."]] as const;
const arabicBenefits = [[Sparkles, "سيارات نظيفة ومصانة", "يتم تجهيز كل سيارة لتمنحك تجربة مريحة ومطمئنة."], [MessageCircle, "استجابة سريعة عبر واتساب", "تحصل بسرعة على معلومات التوفر والسعر."], [CarFront, "خدمة محلية في سيدي قاسم", "وكالة قريبة من عملائها ومتاحة لمرافقتهم."], [ClipboardCheck, "شروط واضحة", "يتم توضيح المعلومات المهمة قبل التأكيد."], [ShieldCheck, "سيارات تناسب احتياجاتك", "موديلات اقتصادية ومدنية وسيدان وSUV لمسارات متنوعة."], [UserRoundCheck, "مرافقة شخصية", "فريقنا يرشدك قبل وأثناء فترة الكراء."]] as const;

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

export function HowItWorksSection({ rtl = false }: { rtl?: boolean }) {
  const ref = useRef<HTMLElement>(null); const reduceMotion = useReducedMotion(); const [activeStep, setActiveStep] = useState(0);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start 78%", "end 40%"] });
  useMotionValueEvent(scrollYProgress, "change", value => { if (!reduceMotion) setActiveStep(Math.min(3, Math.max(0, Math.floor(value * 4)))); });
  const lineProgress = useTransform(scrollYProgress, [0, 0.85], [0, 1]);
  const copy = rtl ? { eyebrow: "حجز بسيط", title: "احجز سيارتك في خطوات بسيطة", description: "خطوات سريعة وواضحة لاختيار سيارتك والتحقق من توفرها وتأكيد حجزك.", availability: "تحقق من التوفر", whatsapp: "تحدث معنا عبر واتساب" } : { eyebrow: "RÉSERVATION SIMPLE", title: "Réservez votre voiture en quelques étapes", description: "Un processus rapide et clair pour trouver votre véhicule, vérifier sa disponibilité et confirmer votre réservation.", availability: "Vérifier la disponibilité", whatsapp: "Parler avec nous sur WhatsApp" };
  const steps = rtl ? arabicSteps : frenchSteps;
  return <section ref={ref} id="fonctionnement" className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8" dir={rtl ? "rtl" : "ltr"}><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.16 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.11 } } }}><motion.p variants={reveal} transition={{ duration: 0.45 }} className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">{copy.eyebrow}</motion.p><motion.h2 variants={reveal} transition={{ duration: 0.55 }} className="mt-2 max-w-2xl text-3xl font-black tracking-tight text-[#10233c] sm:text-4xl">{copy.title}</motion.h2><motion.p variants={reveal} transition={{ duration: 0.5 }} className="mt-4 max-w-2xl leading-7 text-slate-600">{copy.description}</motion.p>
    <div className="relative mt-10 lg:mt-14"><div className="absolute bottom-7 top-7 w-px bg-slate-200 ltr:left-6 rtl:right-6 lg:bottom-auto lg:left-12 lg:right-12 lg:top-9 lg:h-px lg:w-auto"/><motion.div aria-hidden="true" className="absolute bottom-7 top-7 w-px origin-top bg-[#0b5aa7] ltr:left-6 rtl:right-6 lg:hidden" style={reduceMotion ? { scaleY: 1 } : { scaleY: lineProgress }} /><motion.div aria-hidden="true" className="absolute bottom-auto left-12 right-12 top-9 hidden h-px origin-left bg-[#0b5aa7] lg:block" style={reduceMotion ? { scaleX: 1 } : { scaleX: lineProgress }} />
      <div className="grid gap-7 lg:grid-cols-4 lg:gap-6">{steps.map(([Icon, title, description], index) => { const active = reduceMotion || activeStep >= index; return <motion.article key={title} initial={{ opacity: 0, y: reduceMotion ? 0 : 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.46, delay: reduceMotion ? 0 : index * 0.12 }} className="relative flex gap-4 lg:block"><motion.div animate={{ backgroundColor: active ? "#0b5aa7" : "#e2e8f0", color: active ? "#ffffff" : "#64748b", scale: active && !reduceMotion ? 1 : 0.96 }} transition={{ duration: 0.35 }} className="relative z-10 grid size-12 shrink-0 place-items-center rounded-2xl text-sm font-black shadow-sm lg:mx-auto"><span>{String(index + 1).padStart(2, "0")}</span></motion.div><div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_8px_25px_rgba(15,35,60,.05)] lg:mt-6 lg:min-h-[205px]"><motion.div initial={{ scale: reduceMotion ? 1 : 0.9, opacity: 0 }} whileInView={{ scale: 1, opacity: 1 }} viewport={{ once: true }} transition={{ duration: 0.35, delay: reduceMotion ? 0 : index * 0.12 }} className="grid size-9 place-items-center rounded-xl bg-blue-50 text-[#0b5aa7]"><Icon className="size-4"/></motion.div><h3 className="mt-4 text-lg font-bold text-[#10233c]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div></motion.article>})}</div>
    </div><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.45 }} className="mt-10 flex flex-col gap-3 sm:flex-row"><a href="#reservation" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#0b5aa7] px-5 py-3 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#084a8a]">{copy.availability}</a><WhatsAppLink message={generalWhatsAppMessage} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#10233c] transition hover:-translate-y-0.5 hover:shadow-md">{copy.whatsapp}</WhatsAppLink></motion.div>
  </motion.div></section>;
}

export function WhyChooseSection({ rtl = false }: { rtl?: boolean }) {
  const reduceMotion = useReducedMotion(); const reasons = rtl ? arabicBenefits : frenchBenefits;
  const copy = rtl ? { eyebrow: "لماذا Vay Cars", title: "كراء بسيط، موثوق وبدون تعقيد", description: "ترافقك Vay Cars Location بخدمة محلية وسيارات عملية وتواصل سريع.", cars: "اكتشف سياراتنا", route: "/ar/cars" } : { eyebrow: "POURQUOI VAY CARS", title: "Une location simple, fiable et sans complications", description: "Vay Cars Location vous accompagne avec un service local, des véhicules pratiques et une communication rapide.", cars: "Découvrir nos voitures", route: "/fr/voitures" };
  return <section id="avantages" className="relative overflow-hidden bg-[#10233c] py-20 text-white" dir={rtl ? "rtl" : "ltr"}><div aria-hidden="true" className="absolute -right-32 top-0 size-96 rounded-full bg-blue-400/10 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.1 } } }}><motion.p variants={reveal} transition={{ duration: 0.45 }} className="text-sm font-bold uppercase tracking-[.16em] text-blue-200">{copy.eyebrow}</motion.p><motion.h2 variants={reveal} transition={{ duration: 0.55 }} className="mt-2 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">{copy.title}</motion.h2><motion.p variants={reveal} transition={{ duration: 0.48 }} className="mt-4 max-w-2xl leading-7 text-slate-300">{copy.description}</motion.p><div className="mt-10 -mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:grid sm:grid-cols-2 sm:gap-5 sm:overflow-visible sm:px-0 lg:grid-cols-3">{reasons.map(([Icon, title, description], index) => <motion.article key={title} initial={{ opacity: 0, y: reduceMotion ? 0 : 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ duration: 0.45, delay: reduceMotion ? 0 : index * 0.08 }} whileHover={reduceMotion ? {} : { y: -4 }} className="group relative min-h-[225px] w-[86vw] max-w-[380px] shrink-0 snap-start rounded-2xl border border-white/10 bg-white/[.055] p-6 transition hover:border-blue-300/40 hover:bg-white/[.08] hover:shadow-xl sm:w-auto sm:max-w-none"><span className="absolute right-5 top-4 text-xs font-black tracking-widest text-blue-200/50">0{index + 1}</span><div className="grid size-11 place-items-center rounded-xl bg-blue-400/15 text-blue-200 transition group-hover:bg-blue-400/25"><Icon className="size-5"/></div><h3 className="mt-5 max-w-[85%] text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{description}</p></motion.article>)}</div><div className="mt-4 flex justify-center gap-1.5 sm:hidden" aria-hidden="true">{reasons.map((_, index) => <span className={`h-1.5 rounded-full ${index === 0 ? "w-5 bg-blue-300" : "w-1.5 bg-white/30"}`} key={index}/>)}</div><motion.div variants={reveal} transition={{ duration: 0.45 }} className="mt-10"><Link href={copy.route} className="group inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#10233c] transition hover:-translate-y-0.5 hover:shadow-lg">{copy.cars}{rtl ? <ArrowLeft className="size-4 transition-transform group-hover:-translate-x-0.5"/> : <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5"/>}</Link></motion.div></motion.div></div></section>;
}
