"use client";

import Link from "next/link";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, CalendarDays, CarFront, CheckCircle2, MessageCircle, Sparkles } from "lucide-react";
import { useAgencySettings } from "./agency-settings-provider";

const frenchSteps = [[CarFront, "Choisissez votre véhicule", "Parcourez les modèles disponibles."], [CalendarDays, "Indiquez vos dates", "Ajoutez départ et retour."], [MessageCircle, "Recevez votre tarif", "Nous confirmons disponibilité et prix."], [CheckCircle2, "Confirmez sur WhatsApp", "Finalisez votre réservation simplement."]] as const;
const arabicSteps = [[CarFront, "اختر سيارتك", "شوف الطوموبيلات المتوفرة."], [CalendarDays, "حدد تواريخك", "دخل تاريخ الخروج والرجوع."], [MessageCircle, "احصل على عرضك", "نأكدولك التوفر والثمن."], [CheckCircle2, "أكد عبر واتساب", "كمل الحجز ديالك بسهولة."]] as const;

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

export function HowItWorksSection({ rtl = false }: { rtl?: boolean }) {
  const reduceMotion = useReducedMotion();
  const copy = rtl ? { eyebrow: "حجز بسيط", title: "احجز طوموبيلتك فخطوات بسيطة", description: "اختار الطوموبيل، دخل التواريخ، وخذ التأكيد ديالك بسرعة." } : { eyebrow: "RÉSERVATION SIMPLE", title: "Réservez votre voiture en quelques étapes", description: "Choisissez votre véhicule, indiquez vos dates et recevez rapidement votre confirmation." };
  const steps = rtl ? arabicSteps : frenchSteps;
  return <section id="fonctionnement" className="mx-auto max-w-7xl scroll-mt-20 px-4 py-12 sm:px-6 sm:py-16 lg:px-8" dir={rtl ? "rtl" : "ltr"}><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.16 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.09 } } }}><motion.p variants={reveal} transition={{ duration: 0.45 }} className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">{copy.eyebrow}</motion.p><motion.h2 variants={reveal} transition={{ duration: 0.55 }} className="mt-2 max-w-2xl text-[1.75rem] font-black leading-tight tracking-tight text-[#10233c] min-[360px]:text-3xl sm:text-4xl">{copy.title}</motion.h2><motion.p variants={reveal} transition={{ duration: 0.45 }} className="mt-3 max-w-2xl leading-7 text-slate-600">{copy.description}</motion.p>
    <div className="relative mt-7 sm:mt-9"><div aria-hidden="true" className="absolute bottom-7 top-7 w-px bg-slate-200 ltr:left-6 rtl:right-6 lg:bottom-auto lg:left-12 lg:right-12 lg:top-6 lg:h-px lg:w-auto"/>
      <div className="grid gap-4 lg:grid-cols-4 lg:gap-5">{steps.map(([Icon, title, description], index) => <motion.article key={title} initial={{ opacity: 0, y: reduceMotion ? 0 : 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 0.42, delay: reduceMotion ? 0 : index * 0.08 }} className="relative flex gap-4 lg:flex-col lg:gap-0"><div className="relative z-10 grid size-12 shrink-0 place-items-center rounded-2xl bg-[#0b5aa7] text-sm font-black text-white shadow-sm lg:mx-auto"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_8px_25px_rgba(15,35,60,.05)] lg:mt-4"><div className="grid size-9 place-items-center rounded-xl bg-blue-50 text-[#0b5aa7]"><Icon aria-hidden="true" className="size-4"/></div><h3 className="mt-3 text-base font-bold text-[#10233c]">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{description}</p></div></motion.article>)}</div>
    </div>
  </motion.div></section>;
}

export function WhyChooseSection({ rtl = false }: { rtl?: boolean }) {
  const settings = useAgencySettings();
  const reduceMotion = useReducedMotion();
  const reasons = rtl ? [[Sparkles, "طوموبيلات نقية ومصانة", "كل طوموبيل كتوجد باش تكون الرحلة ديالك مريحة ومطمئنة."], [MessageCircle, "جواب سريع فالواتساب", "خد بسرعة معلومات التوفر والثمن بلا تعقيد."], [CarFront, `خدمة قريبة ف${settings.city}`, "وكالة قريبة من الزبناء وواجدة تعاونهم."]] as const : [[Sparkles, "Véhicules propres et entretenus", "Chaque voiture est préparée pour une expérience confortable et rassurante."], [MessageCircle, "Réponse rapide sur WhatsApp", "Recevez rapidement les informations sur la disponibilité et le tarif."], [CarFront, `Service local à ${settings.city}`, "Une agence proche de ses clients et disponible pour les accompagner."]] as const;
  const copy = rtl ? { eyebrow: "لماذا Vay Cars", title: "كراء بسيط، موثوق وبدون تعقيد", description: "خدمة محلية وسيارات عملية وتواصل سريع.", cars: "اكتشف Vay Cars", route: "/ar/about" } : { eyebrow: "POURQUOI VAY CARS", title: "Une location simple, fiable et sans complications", description: "Un service local, des véhicules pratiques et une communication rapide.", cars: "Découvrir Vay Cars", route: "/fr/a-propos" };
  return <section id="avantages" className="relative scroll-mt-20 overflow-hidden bg-[#10233c] py-12 text-white sm:py-16" dir={rtl ? "rtl" : "ltr"}><div aria-hidden="true" className="absolute -right-32 top-0 size-96 rounded-full bg-blue-400/10 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.1 } } }}><motion.p variants={reveal} transition={{ duration: 0.45 }} className="text-sm font-bold uppercase tracking-[.16em] text-blue-200">{copy.eyebrow}</motion.p><motion.h2 variants={reveal} transition={{ duration: 0.55 }} className="mt-2 max-w-2xl text-[1.75rem] font-black leading-tight tracking-tight min-[360px]:text-3xl sm:text-4xl">{copy.title}</motion.h2><motion.p variants={reveal} transition={{ duration: 0.48 }} className="mt-3 max-w-2xl leading-7 text-slate-300">{copy.description}</motion.p><div className="mt-7 grid items-stretch gap-4 sm:grid-cols-3 sm:gap-5">{reasons.map(([Icon, title, description], index) => <motion.article key={title} initial={{ opacity: 0, y: reduceMotion ? 0 : 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ duration: 0.45, delay: reduceMotion ? 0 : index * 0.08 }} whileHover={reduceMotion ? {} : { y: -4 }} className="group relative h-full rounded-2xl border border-white/10 bg-white/[.055] p-5 transition hover:border-blue-300/40 hover:bg-white/[.08] hover:shadow-xl"><div className="grid size-11 place-items-center rounded-xl bg-blue-400/15 text-blue-200 transition group-hover:bg-blue-400/25"><Icon aria-hidden="true" className="size-5"/></div><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-300">{description}</p></motion.article>)}</div><motion.div variants={reveal} transition={{ duration: 0.45 }} className="mt-7"><Link href={copy.route} className="group inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-[#10233c] transition hover:-translate-y-0.5 hover:shadow-lg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white motion-reduce:transform-none">{copy.cars}{rtl ? <ArrowLeft className="size-4 transition-transform group-hover:-translate-x-0.5"/> : <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5"/>}</Link></motion.div></motion.div></div></section>;
}
