import Link from "next/link";
import { MapPin, Phone } from "lucide-react";
import { generalWhatsAppMessage } from "@/lib/whatsapp";
import { WhatsAppLink } from "./whatsapp-link";
import type { PublicSiteSettings } from "@/lib/data/vehicle-mapper";

export function SiteFooter({ rtl = false, settings }: { rtl?: boolean; settings?: PublicSiteSettings }) {
  const copy = rtl ? {
    mobileDescription: "كراء الطوموبيلات فسيدي قاسم.", description: "كرا ديال طوموبيلات عملية، نقية ومريحة فسيدي قاسم. الحجز ساهل وسول على الثمن مباشرة فالواتساب.", navigation: "التنقل", categories: "فئات الطوموبيلات", contact: "تاصل بينا", reserve: "تاصل بينا فالواتساب", legal: "معلومات قانونية", privacy: "سياسة الخصوصية", rights: "© Vay Cars", city: "سيدي قاسم", mobileNav: [["الرئيسية", "/ar"], ["الطوموبيلات", "/ar/cars"], ["شروط الكراء", "/ar#conditions"], ["تاصل بينا", "/ar#contact"]], nav: [["الرئيسية", "/ar"], ["الطوموبيلات", "/ar/cars"], ["الأسئلة", "/ar#faq"], ["تاصل بينا", "/ar#contact"]], categoriesList: ["طوموبيلات صغار", "سيدان", "SUV"], language: "Français", languageHref: "/fr",
  } : {
    mobileDescription: "Location de voitures à Sidi Kacem.", description: "Location de voitures pratiques, propres et confortables à Sidi Kacem. Réservation simple et demande de tarif directement sur WhatsApp.", navigation: "Navigation", categories: "Catégories de véhicules", contact: "Contact", reserve: "WhatsApp", legal: "Mentions légales", privacy: "Politique de confidentialité", rights: "© Vay Cars", city: "Sidi Kacem", mobileNav: [["Accueil", "/fr"], ["Voitures", "/fr/voitures"], ["Conditions", "/fr#conditions"], ["Contact", "/fr#contact"]], nav: [["Accueil", "/fr"], ["Nos voitures", "/fr/voitures"], ["Questions fréquentes", "/fr#faq"], ["Contact", "/fr#contact"]], categoriesList: ["Citadines", "Berlines", "SUV"], language: "العربية", languageHref: "/ar",
  };
  const phone = settings?.phone ?? "06 84 04 01 55";
  const whatsapp = settings?.whatsappNumber ?? "212684040155";
  const place = `${settings?.city ?? "Sidi Kacem"}, ${settings?.country ?? "Maroc"}`;

  return <footer className="bg-[#0e223d] pb-[calc(5.5rem+env(safe-area-inset-bottom))] text-slate-300 md:pb-0" dir={rtl ? "rtl" : "ltr"}>
    <div className="mx-auto max-w-7xl px-4 py-8 md:hidden">
      <Link href={rtl ? "/ar" : "/fr"} className="inline-flex items-center gap-2.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0e223d]"><span className="grid size-9 place-items-center rounded-xl bg-[#0b5aa7] text-sm font-black text-white">V</span><span className="text-lg font-bold text-white">Vay Cars</span></Link>
      <p className="mt-3 text-sm leading-6 text-slate-300">{copy.mobileDescription}</p>
      <nav aria-label={copy.navigation} className="mt-5 grid grid-cols-2 gap-x-4 gap-y-1 text-sm font-medium"><>{copy.mobileNav.map(([label, href]) => <Link key={href} href={href} className="min-h-10 py-2 transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300">{label}</Link>)}</></nav>
      <div className="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-4"><p className="inline-flex items-center gap-1.5 text-sm"><MapPin className="size-4 shrink-0 text-blue-300" aria-hidden="true" />{copy.city}</p><WhatsAppLink message={generalWhatsAppMessage} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#16a34a] px-3 py-2 text-sm font-bold text-white transition hover:bg-[#15803d] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"><span>{copy.reserve}</span></WhatsAppLink></div>
      <div className="mt-4 flex items-center justify-between gap-3 border-t border-white/10 pt-4 text-xs text-slate-400"><p>{copy.rights}</p><div className="flex gap-4"><Link href="#" className="transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300">{copy.legal}</Link><Link href="#" className="transition hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-300">{copy.privacy}</Link></div></div>
    </div>

    <div className="hidden md:block"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-14 lg:grid-cols-[1.35fr_.8fr_.9fr_1fr] lg:gap-8 lg:px-8"><div><Link href={rtl ? "/ar" : "/fr"} className="inline-flex items-center gap-2.5"><span className="grid size-10 place-items-center rounded-xl bg-[#0b5aa7] text-base font-black text-white">V</span><span className="text-xl font-bold text-white">Vay Cars</span></Link><p className="mt-4 max-w-sm text-sm leading-6">{copy.description}</p><WhatsAppLink message={generalWhatsAppMessage} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#16a34a] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#15803d]">{copy.reserve}</WhatsAppLink></div><div><h2 className="text-sm font-bold uppercase tracking-[.14em] text-white">{copy.navigation}</h2><nav className="mt-4 flex flex-col items-start gap-3 text-sm"><Link href={copy.languageHref} className="text-blue-200 transition hover:text-white">{copy.language}</Link>{copy.nav.map(([label, href]) => <Link key={href} href={href} className="transition hover:text-white">{label}</Link>)}</nav></div><div><h2 className="text-sm font-bold uppercase tracking-[.14em] text-white">{copy.categories}</h2><ul className="mt-4 space-y-3 text-sm">{copy.categoriesList.map((category) => <li key={category}>{category}</li>)}</ul></div><div><h2 className="text-sm font-bold uppercase tracking-[.14em] text-white">{copy.contact}</h2><address className="mt-4 space-y-3 text-sm not-italic"><p className="flex items-start gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-blue-300" />{place}</p><a href={`tel:+212${phone.replace(/\D/g, "").replace(/^0/, "")}`} className="flex items-center gap-2 transition hover:text-white"><Phone className="size-4 shrink-0 text-blue-300" />{phone}</a><a href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" className="flex items-center gap-2 transition hover:text-white" aria-label="WhatsApp">WhatsApp</a></address></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 text-xs text-slate-400 lg:px-8"><p>{copy.rights}</p><div className="flex gap-5"><Link href="#" className="transition hover:text-white">{copy.legal}</Link><Link href="#" className="transition hover:text-white">{copy.privacy}</Link></div></div></div></div>
  </footer>;
}
