"use client";

import Link from "next/link";
import { AnimatePresence, LayoutGroup, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, CarFront } from "lucide-react";
import { useMemo, useState } from "react";
import type { PublicVehicle } from "@/lib/data/vehicle-mapper";
import { VehicleCard } from "./vehicle-card";

type FilterId = "all" | "citadine" | "economique" | "berline" | "suv" | "MANUAL" | "AUTOMATIC";
const filterIds: FilterId[] = ["all", "citadine", "economique", "berline", "suv", "MANUAL", "AUTOMATIC"];

export function VehicleCatalogue({ vehicles, rtl = false, embedded = false }: { vehicles: PublicVehicle[]; rtl?: boolean; embedded?: boolean }) {
  const [activeFilter, setActiveFilter] = useState<FilterId>("all");
  const reduceMotion = useReducedMotion();
  const copy = rtl ? { eyebrow: "أسطولنا", title: "اختر السيارة المناسبة لرحلتك", description: "سيارات اقتصادية ومريحة وعملية للمدينة، للتنقلات المهنية والرحلات العائلية.", all: "الكل", labels: { citadine: "سيارات المدينة", economique: "اقتصادية", berline: "سيدان", suv: "SUV", MANUAL: "يدوية", AUTOMATIC: "أوتوماتيك" }, empty: "لا توجد سيارة متاحة في هذه الفئة في الوقت الحالي.", reset: "عرض كل السيارات", viewAll: "عرض جميع السيارات", route: "/ar/cars" } : { eyebrow: "NOTRE FLOTTE", title: "Choisissez la voiture adaptée à votre trajet", description: "Des véhicules économiques, confortables et pratiques pour la ville, les déplacements professionnels et les voyages en famille.", all: "Toutes", labels: { citadine: "Citadine", economique: "Économique", berline: "Berline", suv: "SUV", MANUAL: "Manuelle", AUTOMATIC: "Automatique" }, empty: "Aucun véhicule disponible dans cette catégorie pour le moment.", reset: "Voir toutes les voitures", viewAll: "Voir toutes les voitures", route: "/fr/voitures" };
  const label = (filter: FilterId) => filter === "all" ? copy.all : copy.labels[filter];
  const filtered = useMemo(() => vehicles.filter(vehicle => activeFilter === "all" || (activeFilter === "economique" ? vehicle.isEconomy : activeFilter === "MANUAL" || activeFilter === "AUTOMATIC" ? vehicle.transmissionCode === activeFilter : vehicle.categorySlug === activeFilter)).sort((a, b) => a.displayOrder - b.displayOrder), [activeFilter, vehicles]);
  const intro = { hidden: { opacity: 0, y: reduceMotion ? 0 : 16 }, visible: { opacity: 1, y: 0 } };
  return <section id={embedded ? "voitures" : undefined} className={embedded ? "mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8" : "mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"} dir={rtl ? "rtl" : "ltr"}>
    <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.09 } } }}>
      <motion.p variants={intro} transition={{ duration: 0.45, ease: "easeOut" }} className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">{copy.eyebrow}</motion.p>
      <motion.h2 variants={intro} transition={{ duration: 0.52, ease: "easeOut" }} className="mt-2 max-w-2xl text-3xl font-black tracking-tight text-[#10233c] sm:text-4xl">{copy.title}</motion.h2>
      <motion.p variants={intro} transition={{ duration: 0.48, ease: "easeOut" }} className="mt-4 max-w-2xl leading-7 text-slate-600">{copy.description}</motion.p>
      <motion.div variants={intro} transition={{ duration: 0.48, ease: "easeOut" }} className="-mx-4 mt-7 overflow-x-auto px-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><LayoutGroup id={rtl ? "arabic-vehicle-filters" : "vehicle-filters"}><div className="flex w-max min-w-full gap-2 pb-1 sm:flex-wrap">{filterIds.map(filter => <button key={filter} type="button" aria-pressed={activeFilter === filter} onClick={() => setActiveFilter(filter)} className={`relative shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0b5aa7] ${activeFilter === filter ? "text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-blue-200 hover:text-[#0b5aa7]"}`}>{activeFilter === filter && <motion.span layoutId={rtl ? "arabic-active-filter" : "active-filter"} transition={reduceMotion ? { duration: 0 } : { type: "spring", stiffness: 380, damping: 30 }} className="absolute inset-0 rounded-xl bg-[#0b5aa7]"/>}<span className="relative">{label(filter)}</span></button>)}</div></LayoutGroup></motion.div>
      <motion.div variants={intro} transition={{ duration: 0.5, ease: "easeOut" }} className="mt-8"><AnimatePresence mode="popLayout" initial={false}>{filtered.length ? <motion.div layout={!reduceMotion} className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:grid sm:grid-cols-2 sm:gap-6 sm:overflow-visible sm:px-0 lg:grid-cols-3">{filtered.map((vehicle, index) => <div className="w-[86vw] max-w-[390px] shrink-0 snap-start sm:w-auto sm:max-w-none" key={vehicle.id}><VehicleCard vehicle={vehicle} rtl={rtl} index={index} priority={!embedded && index === 0}/></div>)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center"><CarFront className="mx-auto size-8 text-[#0b5aa7]"/><p className="mt-3 font-bold text-[#10233c]">{copy.empty}</p><button onClick={() => setActiveFilter("all")} className="mt-5 rounded-xl bg-[#0b5aa7] px-4 py-2.5 text-sm font-bold text-white">{copy.reset}</button></motion.div>}</AnimatePresence>{filtered.length > 1 && <div className="mt-4 flex justify-center gap-1.5 sm:hidden" aria-hidden="true">{filtered.map((vehicle, index) => <span key={vehicle.id} className={`h-1.5 rounded-full ${index === 0 ? "w-5 bg-[#0b5aa7]" : "w-1.5 bg-slate-300"}`}/>)}</div>}</motion.div>
      {embedded && <motion.div variants={intro} transition={{ duration: 0.45, ease: "easeOut" }} className="mt-9 text-center"><Link href={copy.route} className="group inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 font-bold text-[#10233c] transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md">{copy.viewAll}{rtl ? <ArrowLeft className="size-4 transition-transform group-hover:-translate-x-0.5"/> : <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5"/>}</Link></motion.div>}
    </motion.div>
  </section>;
}
