"use client";

import Link from "next/link";
import { AnimatePresence, LayoutGroup, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ArrowRight, CarFront } from "lucide-react";
import { useMemo, useState } from "react";
import { getCatalogueFilterLabel, matchesCatalogueFilter, type CatalogueFilterConfig, type CatalogueFilterId } from "@/lib/catalogue-filters";
import type { PublicVehicle } from "@/lib/data/vehicle-mapper";
import { VehicleCard } from "./vehicle-card";

export function VehicleCatalogue({ vehicles, filters, rtl = false, embedded = false }: { vehicles: PublicVehicle[]; filters: CatalogueFilterConfig[]; rtl?: boolean; embedded?: boolean }) {
  const [activeFilter, setActiveFilter] = useState<CatalogueFilterId>("all");
  const reduceMotion = useReducedMotion();
  const copy = rtl ? { eyebrow: "الطوموبيلات ديالنا", title: "اختار الطوموبيل اللي ناسبك", description: "طوموبيلات اقتصادية، مريحة وعملية للمدينة، الخدمة ومشاوير العائلة.", empty: "ما كايناش طوموبيل متوفرة دابا فهاد الفئة.", reset: "شوف كاع الطوموبيلات", viewAll: "شوف كاع الطوموبيلات", route: "/ar/cars" } : { eyebrow: "NOTRE FLOTTE", title: "Choisissez la voiture adaptée à votre trajet", description: "Des véhicules économiques, confortables et pratiques pour la ville, les déplacements professionnels et les voyages en famille.", empty: "Aucun véhicule disponible dans cette catégorie pour le moment.", reset: "Voir toutes les voitures", viewAll: "Voir toutes les voitures", route: "/fr/voitures" };
  const filtered = useMemo(() => vehicles.filter((vehicle) => matchesCatalogueFilter(vehicle, activeFilter)).sort((a, b) => a.displayOrder - b.displayOrder), [activeFilter, vehicles]);
  const intro = { hidden: { opacity: 0, y: reduceMotion ? 0 : 16 }, visible: { opacity: 1, y: 0 } };
  return <section id={embedded ? "voitures" : undefined} className={embedded ? "mx-auto max-w-7xl scroll-mt-20 px-4 py-12 sm:px-6 sm:py-16 lg:px-8" : "mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-16 lg:px-8"} dir={rtl ? "rtl" : "ltr"}>
    <motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, visible: { transition: { staggerChildren: reduceMotion ? 0 : 0.09 } } }}>
      <motion.p variants={intro} transition={{ duration: 0.45, ease: "easeOut" }} className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">{copy.eyebrow}</motion.p>
      <motion.h2 variants={intro} transition={{ duration: 0.52, ease: "easeOut" }} className="mt-2 max-w-2xl text-[1.75rem] font-black leading-tight tracking-tight text-[#10233c] min-[360px]:text-3xl sm:text-4xl">{copy.title}</motion.h2>
      <motion.p variants={intro} transition={{ duration: 0.48, ease: "easeOut" }} className="mt-4 max-w-2xl leading-7 text-slate-600">{copy.description}</motion.p>
      <motion.div variants={intro} transition={{ duration: 0.48, ease: "easeOut" }} className="-mx-4 mt-5 overflow-x-auto px-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mt-7"><LayoutGroup id={rtl ? "arabic-vehicle-filters" : "vehicle-filters"}><div className="flex w-max min-w-full gap-2 pb-1 sm:flex-wrap">{filters.map((filter) => <button key={filter.id} type="button" aria-pressed={activeFilter === filter.id} onClick={() => setActiveFilter(filter.id)} className={`relative inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0b5aa7] ${activeFilter === filter.id ? "text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-blue-200 hover:text-[#0b5aa7]"}`}>{activeFilter === filter.id && <motion.span layoutId={rtl ? "arabic-active-filter" : "active-filter"} transition={reduceMotion ? { duration: 0 } : { type: "spring", stiffness: 380, damping: 30 }} className="absolute inset-0 rounded-xl bg-[#0b5aa7]"/>}{filter.icon && <span aria-hidden="true" className="relative">{filter.icon}</span>}<span className="relative">{getCatalogueFilterLabel(filter, rtl)}</span></button>)}</div></LayoutGroup></motion.div>
      <motion.div variants={intro} transition={{ duration: 0.5, ease: "easeOut" }} className="mt-7 sm:mt-8"><AnimatePresence mode="popLayout" initial={false}>{filtered.length ? <motion.div layout={!reduceMotion} aria-label={rtl ? "لائحة الطوموبيلات، جر باش تشوف المزيد" : "Liste de véhicules, faites défiler pour en voir plus"} className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:mx-0 sm:grid sm:grid-cols-2 sm:gap-6 sm:overflow-visible sm:px-0 lg:grid-cols-3">{filtered.map((vehicle, index) => <div className="w-[calc(100vw-2.5rem)] max-w-[390px] shrink-0 snap-start sm:w-auto sm:max-w-none" key={vehicle.id}><VehicleCard vehicle={vehicle} rtl={rtl} index={index} priority={!embedded && index === 0}/></div>)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-12 text-center"><CarFront className="mx-auto size-8 text-[#0b5aa7]"/><p className="mt-3 font-bold text-[#10233c]">{copy.empty}</p><button onClick={() => setActiveFilter("all")} className="mt-5 min-h-11 rounded-xl bg-[#0b5aa7] px-4 py-2.5 text-sm font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0b5aa7]">{copy.reset}</button></motion.div>}</AnimatePresence></motion.div>
      {embedded && <motion.div variants={intro} transition={{ duration: 0.45, ease: "easeOut" }} className="mt-7 text-center sm:mt-9"><Link href={copy.route} className="group inline-flex min-h-12 items-center gap-2 rounded-xl border border-slate-300 bg-white px-5 py-3 font-bold text-[#10233c] transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0b5aa7] motion-reduce:transform-none">{copy.viewAll}{rtl ? <ArrowLeft className="size-4 transition-transform group-hover:-translate-x-0.5"/> : <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5"/>}</Link></motion.div>}
    </motion.div>
  </section>;
}
