import Image from "next/image";
import Link from "next/link";
import { CarFront, CheckCircle2, Star, Wrench, XCircle, CalendarClock, ListTree } from "lucide-react";
import { getAdminDashboardStats, getRecentAdminVehicles } from "@/lib/admin/dashboard";

const iconClass = "size-5 text-[#0b5aa7]";
export default async function AdminPage() {
  const [stats, recent] = await Promise.all([getAdminDashboardStats(), getRecentAdminVehicles()]);
  const cards = [[CarFront, "Total véhicules", stats.totalVehicles, "Tous les véhicules enregistrés."], [CheckCircle2, "Véhicules actifs", stats.activeVehicles, "Visibles dans la gestion publique."], [CheckCircle2, "Disponibles", stats.availableVehicles, "Statut actuellement disponible."], [XCircle, "Indisponibles", stats.unavailableVehicles, "À proposer avec une alternative."], [Wrench, "En entretien", stats.maintenanceVehicles, "À contrôler avant publication."], [CalendarClock, "Réservées", stats.reservedVehicles, "Statut réservé."], [Star, "Mis en avant", stats.featuredVehicles, "Présents dans la sélection."], [ListTree, "Catégories", stats.totalCategories, "Catégories enregistrées."]] as const;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0b5aa7]">Tableau de bord</p><h1 className="mt-2 text-3xl font-black text-[#10233c]">Vue d’ensemble</h1></div><div className="flex flex-wrap gap-2"><Link href="/admin/vehicles/new" className="rounded-xl bg-[#0b5aa7] px-4 py-2.5 text-sm font-bold text-white">Ajouter une voiture</Link><Link href="/admin/vehicles" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-[#10233c]">Gérer les véhicules</Link></div></div><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon, label, count, detail]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className={iconClass} /><p className="mt-4 text-3xl font-black text-[#10233c]">{count}</p><h2 className="mt-1 font-bold text-[#10233c]">{label}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></article>)}</section><section className="mt-8 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><h2 className="font-bold text-[#10233c]">Véhicules récemment mis à jour</h2><Link href="/admin/vehicles" className="text-sm font-bold text-[#0b5aa7]">Voir tous</Link></div><div className="divide-y divide-slate-100">{recent.map((vehicle) => <div key={vehicle.id} className="flex items-center gap-4 px-5 py-4"><div className="relative size-12 shrink-0 overflow-hidden rounded-xl bg-slate-100">{vehicle.image && <Image src={vehicle.image} alt={vehicle.alt} fill sizes="48px" className="object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-[#10233c]">{vehicle.brand} {vehicle.model}</p><p className="text-xs text-slate-500">{vehicle.availability} · {vehicle.active ? "Active" : "Masquée"} · {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(vehicle.updatedAt))}</p></div><Link href={`/admin/vehicles/${vehicle.id}/edit`} className="text-sm font-bold text-[#0b5aa7]">Modifier</Link></div>)}</div></section><section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Gérer les catégories", "/admin/categories"], ["Paramètres de l’agence", "/admin/settings"], ["Voir le site public", "/fr"], ["Gérer les véhicules", "/admin/vehicles"]].map(([label, href]) => <Link key={href} href={href} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-[#10233c] shadow-sm hover:border-blue-200">{label}</Link>)}</section></main>;
}
